image: node:10.13.0

pipelines:
  default:
    - step:
        name: Lint
        caches:
          - node 
        script:
          - npm install
          - npm run lint
  branches:
    master:
        - step:
            name: Upload template through dashboard
            script:
              - npm run pipeline
              # - node /usr/local/lib/node_modules/design-framework-cli/src/index.js push -e auto
    release/*:
        - step:
            name: Release and Upload              - globalnodev4
            script:
              - npm run pipeline
              - node /usr/local/lib/node_modules/design-framework-cli/src/index.js fly topup
              # - node /usr/local/lib/node_modules/design-framework-cli/src/index.js push -e auto
    test-branch:
        - step:
            name: Release candidate              - globalnodev4
            script:
              - npm run pipeline
              - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
              - git fetch
              - git checkout package-lock.json
              - node /usr/local/lib/node_modules/design-framework-cli/src/index.js fly stage
  custom:
    upload:
      - step:
          name: Upload template through dashboard
          caches:
            - globalnodev4
          script:
            - npm run pipeline
            - node /usr/local/lib/node_modules/design-framework-cli/src/index.js push -e auto -f true
    bundle:
      - step:
          name: Bundle the template and share it through slack
          caches:
            - globalnodev4
          script:
            - npm run pipeline
            - node /usr/local/lib/node_modules/design-framework-cli/src/index.js push -u false -f true
    finish:
      - step:
          name: Merge release to master
          caches:
            - globalnodev4
          script:
            - npm run pipeline
            - echo $MSG
            - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
            - git fetch
            - git checkout package-lock.json
            - node /usr/local/lib/node_modules/design-framework-cli/src/index.js fly finish -m "$MSG"
    topup:
      - step:
          name: Topup release
          caches:
            - globalnodev4
          script:
            - npm run pipeline
            - echo $MSG
            - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
            - git fetch
            - git checkout package-lock.json
            - node /usr/local/lib/node_modules/design-framework-cli/src/index.js fly topup -m "$MSG"
    stage:
      - step:
          name: Release candidate
          caches:
            - globalnodev4
          script:
            - npm run pipeline
            - echo $MSG
            - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
            - git fetch
            - git checkout package-lock.json
            - node /usr/local/lib/node_modules/design-framework-cli/src/index.js fly stage -m "$MSG"
    sync:
      - step:
          name: Merge master to develop
          caches:
            - globalnodev4
          script:
            - npm run pipeline
            - echo $MSG
            - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
            - git fetch
            - git checkout package-lock.json
            - node /usr/local/lib/node_modules/design-framework-cli/src/index.js fly sync -m "$MSG"
    prepare:
      - step:
          name: Prepare for next pipeline
          script:
            - echo $MSG
            - git commit --allow-empty -m "$MSG"
            - git push origin
